USE Ventas
GO

CREATE TABLE Conyuge
(
IdCliente INT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES Cliente,
Dni CHAR(8) NOT NULL,
Nombre VARCHAR(30) NOT NULL,
Apellido VARCHAR(30) NOT NULL,
Edad INT NULL
)

CREATE TABLE BOLETA
(
IdBoleta INT NOT NULL PRIMARY KEY,
NumeroBoleta VARCHAR(20) NOT NULL,
FechaEmision DATE NOT NULL,
IdCliente INT NOT NULL FOREIGN KEY REFERENCES Cliente
)

CREATE TABLE PRODUCTO
(
IdProducto INT NOT NULL PRIMARY KEY,
Descripcion VARCHAR(100) NOT NULL,
Unidad VARCHAR(20) NOT NULL,
PrecioUnitario DECIMAL(5,2) NOT NULL,
Marca VARCHAR(20) NULL
)

CREATE TABLE DETALLE_BOLETA
(
IdBoleta INT NOT NULL,
IdProducto INT NOT NULL,
Cantidad INT NOT NULL
)

ALTER TABLE DETALLE_BOLETA
ADD PRIMARY KEY (IdBoleta, IdProducto)

ALTER TABLE DETALLE_BOLETA
ADD FOREIGN KEY (IdBoleta) REFERENCES BOLETA

ALTER TABLE DETALLE_BOLETA
ADD FOREIGN KEY (IdProducto) REFERENCES PRODUCTO
